name: nginx-conf-deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.SSHKEY }}
          script: >
            cd ${{ secrets.PATH }} 
            && git pull 
            && service nginx reload
